language: node_js
node_js:
  - '10'
sudo: required
dist: xenial

addons:  
  apt:
    packages:
      dpkg
      google-chrome-stable
    
services:
  - xvfb
cache:
  directories:
    - $HOME/.npm

before_script:
  - google-chrome-stable --version

install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
  # run build script specified in package.json
  - npm run ci

after_success:
  - codecov
